Repository twitterdev/twitter-python-ads-sdk, pull requests merged in 2019-11, with the labels that each got.

#234 Add timeout option to Request class for better error handling.
  tests/test_client.py
  twitter_ads/http.py
Labels: feature, improvement

#235 [minor] bug fix
  examples/analytics.py
  examples/media_library.py
  examples/media_upload.py
  twitter_ads/creative.py
Labels: bug

#233 Add validation on Error class
  twitter_ads/error.py
Labels: improvement
